# Generated by Django 3.1.7 on 2021-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='litigation',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Data'),
        ),
    ]
