# Generated by Django 3.1.7 on 2021-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0002_auto_20210428_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='IMU_final_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Dichiarazione fini IMU'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='contract_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Canone contratto'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Importo Iscrizione'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='epoch_construction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Epoca Costruzione (anno)'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='initial_estimation_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Valore Stima Iniziale'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='last_notary_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Ultime spese notarili'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reclamation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Costo bonifica'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='residual_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Affitto residuo'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Valore Obiettivo'),
        ),
    ]
