# Generated by Django 3.1.7 on 2021-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0003_auto_20210503_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='aboveground_quantification',
            field=models.IntegerField(blank=True, default=0, help_text='Number of plants', null=True, verbose_name='Quantificazione Soprasuolo'),
        ),
    ]
