# Generated by Django 3.1.7 on 2021-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0004_auto_20210505_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='aboveground_quantification',
            field=models.IntegerField(blank=True, default=0, help_text='Numero piante', null=True, verbose_name='Quantificazione Soprasuolo'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='Successo'),
        ),
    ]
