# Generated by Django 3.1.7 on 2021-05-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0005_auto_20210505_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='transformation_coefficient',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Coefficiente di trasformazione (volumi)'),
        ),
    ]
