# Generated by Django 3.1.7 on 2021-05-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0006_auto_20210505_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='contract_duration',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Durata contratto (mesi)'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='contract_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Canone contratto'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='extension_MQ',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Estensione MQ'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reclamation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=32, null=True, verbose_name='Costo bonifica'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='residual_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Affitto residuo'),
        ),
    ]
