# Generated by Django 3.1.7 on 2021-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0009_auto_20210505_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Test'),
        ),
    ]
