# Generated by Django 3.1.7 on 2021-11-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0010_litigation_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='test',
        ),
        migrations.AddField(
            model_name='litigation',
            name='superficie_occupata',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Superficie Occupata'),
        ),
    ]
