# Generated by Django 3.1.7 on 2021-11-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0011_auto_20211101_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='initial_estimation_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valore Stima Iniziale'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('Esproprio Residenziale Libera', 'Esproprio Residenziale Libera'), ('Esproprio Industriale Libera', 'Esproprio Industriale Libera'), ('Esproprio Fabbricato Residenziale', 'Esproprio Fabbricato Residenziale'), ('Esproprio Fabbricato Industriale', 'Esproprio Fabbricato Industriale')], default=None, max_length=100, null=True, verbose_name='Tipologia Iscrizione'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='target_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valore Obiettivo'),
        ),
    ]
