# Generated by Django 3.1.7 on 2021-11-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0013_auto_20211101_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='superficie_occupata',
        ),
        migrations.AddField(
            model_name='litigation',
            name='occupied_area',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Superficie Occupata'),
        ),
    ]
