# Generated by Django 3.1.7 on 2021-11-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0014_auto_20211102_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('test', 'test'), ('Esproprio Industriale Libera', 'Esproprio Industriale Libera'), ('Esproprio Fabbricato Residenziale', 'Esproprio Fabbricato Residenziale'), ('Esproprio Fabbricato Industriale', 'Esproprio Fabbricato Industriale')], default=None, max_length=100, null=True, verbose_name='Tipologia Iscrizione'),
        ),
    ]
