# Generated by Django 3.1.7 on 2021-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0015_auto_20211102_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('Esproprio agricolo senza fabbricati', 'Esproprio agricolo senza fabbricati'), ('Esproprio agricolo con fabbricati', 'Esproprio agricolo con fabbricati'), ('Esproprio area destinazione residenziale senza fabbricati', 'Esproprio area destinazione residenziale senza fabbricati'), ('Esproprio area destinazione residenziale con fabbricati', 'Esproprio area destinazione residenziale con fabbricati'), ('Esproprio area destinazione industriale senza fabbricati', 'Esproprio area destinazione industriale senza fabbricati'), ('Esproprio area destinazione industriale con fabbricati', 'Esproprio area destinazione industriale con fabbricati'), ('Area boschiva', 'Area boschiva'), ('Altre destinazioni funzionali', 'Altre destinazioni funzionali')], default=None, max_length=100, null=True, verbose_name='Tipologia Iscrizione'),
        ),
    ]
