# Generated by Django 3.1.7 on 2021-11-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0017_auto_20211105_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='fruit_pendants',
            field=models.CharField(blank=True, choices=[('yes', 'si'), ('no', 'no')], max_length=100, null=True, verbose_name='Frutti Pendenti'),
        ),
    ]
