# Generated by Django 3.1.7 on 2021-11-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0018_auto_20211108_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='area_type',
        ),
        migrations.AlterField(
            model_name='litigation',
            name='fruit_pendants',
            field=models.CharField(blank=True, choices=[('yes', 'si'), ('no', 'no')], default='no', max_length=100, null=True, verbose_name='Frutti Pendenti'),
        ),
    ]
