# Generated by Django 3.1.7 on 2021-11-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('litigations', '0021_auto_20211117_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='dispute_matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputematter', verbose_name='Materia Controversia'),
        ),
    ]
