# Generated by Django 3.1.7 on 2021-11-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0022_auto_20211117_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
    ]
