# Generated by Django 3.1.7 on 2021-11-21 21:36

from django.db import migrations, models
import litigations.models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0023_configuration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AlterField(
            model_name='litigation',
            name='name',
            field=models.CharField(default=litigations.models.increment_litigation_number, max_length=20, unique=True, verbose_name='Litigation Code'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='origin',
            field=models.CharField(blank=True, choices=[('internal', 'interno'), ('web', 'web')], default='internal', max_length=8, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='successful',
            field=models.BooleanField(default=False, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Date'),
        ),
    ]
