# Generated by Django 3.1.7 on 2021-11-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0024_auto_20211121_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='IMU_final_declaration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dichiarazione fini IMU'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Importo Iscrizione'),
        ),
    ]
