# Generated by Django 3.1.7 on 2021-11-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0025_auto_20211129_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='IMU_final_declaration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='Dichiarazione fini IMU'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Importo Iscrizione'),
        ),
    ]
