# Generated by Django 3.1.7 on 2021-12-06 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_auto_20211202_2237'),
        ('configurations', '0002_auto_20211202_2237'),
        ('litigations', '0027_auto_20211202_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='dispute_matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputematter', verbose_name='Controversy Matter'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='dispute_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputeobject', verbose_name='Dispute Object'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Enrollment Amount'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='initial_estimation_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Initial Estimation Value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='prejudicial_registrations',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prejudicial Registrations'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('Esproprio Agricolo', 'Agricultural expropriation'), ('Esproprio Residenziale Libera', 'Esproprio Residenziale Libera'), ('Esproprio Industriale Libera', 'Esproprio Industriale Libera'), ('Esproprio Fabbricato Residenziale', 'Esproprio Fabbricato Residenziale'), ('Esproprio Fabbricato Industriale', 'Esproprio Fabbricato Industriale')], default=None, max_length=100, null=True, verbose_name='Registration Typology'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='residual_surface',
            field=models.FloatField(blank=True, null=True, verbose_name='Residual Surface'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='surface_directly_concerned',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Directly Concerned'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='technical_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Technical Reference'),
        ),
    ]
