# Generated by Django 3.1.7 on 2021-12-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0028_auto_20211206_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='cultivator_type',
            field=models.CharField(blank=True, choices=[('value_one', 'Valore 1'), ('value_two', 'Valore 2')], default='no', max_length=100, null=True, verbose_name='Tipologia Coltivatore'),
        ),
    ]
