# Generated by Django 3.1.7 on 2022-02-06 10:28

from django.db import migrations, models
import django.db.models.deletion
import litigations.models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20220206_1128'),
        ('clients', '0021_auto_20220206_1128'),
        ('litigations', '0030_auto_20211206_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='cultivator_type',
            field=models.CharField(blank=True, choices=[('value_1', 'value-1'), ('value_2', 'value-2')], default='no', max_length=100, null=True, verbose_name='Tipologia Coltivatore'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='dispute_matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputematter', verbose_name='controversy-matter'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='dispute_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputeobject', verbose_name='dispute-object'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='enrollment-amount'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='initial_estimation_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='initial-estimation-value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='name',
            field=models.CharField(default=litigations.models.increment_litigation_number, max_length=20, unique=True, verbose_name='litigation-code'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='prejudicial_registrations',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='prejudicial-registrations'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('Esproprio Agricolo', 'Agricultural expropriation'), ('Esproprio Residenziale Libera', 'Esproprio Residenziale Libera'), ('Esproprio Industriale Libera', 'Esproprio Industriale Libera'), ('Esproprio Fabbricato Residenziale', 'Esproprio Fabbricato Residenziale'), ('Esproprio Fabbricato Industriale', 'Esproprio Fabbricato Industriale')], default=None, max_length=100, null=True, verbose_name='registration-typology'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='surface_directly_concerned',
            field=models.FloatField(blank=True, null=True, verbose_name='surface-directly-concerned'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='target-value'),
        ),
    ]
