# Generated by Django 3.1.7 on 2022-02-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0031_auto_20220206_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='closing_data',
            field=models.CharField(max_length=100, null=True, verbose_name='closing-data'),
        ),
        migrations.AddField(
            model_name='litigation',
            name='starting_data',
            field=models.CharField(max_length=100, null=True, verbose_name='starting-data'),
        ),
        migrations.AddField(
            model_name='litigation',
            name='target_data',
            field=models.CharField(max_length=100, null=True, verbose_name='target-data'),
        ),
    ]
