# Generated by Django 3.1.7 on 2022-02-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0032_auto_20220209_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='final_value'),
        ),
    ]
