# Generated by Django 3.1.7 on 2022-02-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0033_litigation_final_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='final-value'),
        ),
    ]
