# Generated by Django 3.1.7 on 2022-02-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0035_litigation_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='contract',
        ),
    ]
