# Generated by Django 3.1.7 on 2022-02-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0036_remove_litigation_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='reopen',
            field=models.CharField(max_length=100, null=True, verbose_name='reopen'),
        ),
    ]
