# Generated by Django 3.1.7 on 2022-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0037_litigation_reopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='reopen',
            field=models.BooleanField(default=True, verbose_name='reopen'),
        ),
    ]
