# Generated by Django 3.1.7 on 2022-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0040_auto_20220219_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='clossed',
        ),
        migrations.AddField(
            model_name='litigation',
            name='closed',
            field=models.BooleanField(default=True, verbose_name='closed'),
        ),
    ]
