# Generated by Django 3.1.7 on 2022-02-20 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configurations', '0007_auto_20220212_2051'),
        ('lawyers', '0006_auto_20220212_2051'),
        ('litigations', '0041_auto_20220219_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='aboveground_quantification',
        ),
        migrations.RemoveField(
            model_name='litigation',
            name='starting_data',
        ),
        migrations.AddField(
            model_name='litigation',
            name='above_ground_quantification',
            field=models.IntegerField(blank=True, default=0, help_text='Numero piante', null=True, verbose_name='Above Ground Quantification'),
        ),
        migrations.AddField(
            model_name='litigation',
            name='starting_date',
            field=models.DateField(max_length=100, null=True, verbose_name='Starting Date'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='area_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area Address'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='batch_disfiguration',
            field=models.CharField(blank=True, choices=[('yes', 'si'), ('no', 'no')], default='no', max_length=100, null=True, verbose_name='Batch Disfiguration'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='closing_data',
            field=models.CharField(max_length=100, null=True, verbose_name='Closing Data'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='cultivator_type',
            field=models.CharField(blank=True, choices=[('value_1', 'value-1'), ('value_2', 'value-2')], default='no', max_length=100, null=True, verbose_name='Cultivator Type'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='culture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.culturetype', verbose_name='Culture Type'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='date_receipt_act',
            field=models.DateField(blank=True, null=True, verbose_name='Date Receipt Act'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='dispute_matter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputematter', verbose_name='Controversy Matter'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='dispute_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.disputeobject', verbose_name='Dispute Object'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Enrollment Amount'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='final_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='Final Value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='fruit_pendants',
            field=models.CharField(blank=True, choices=[('yes', 'si'), ('no', 'no')], default='no', max_length=100, null=True, verbose_name='Fruit Pendants'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='initial_estimation_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Initial Estimation Value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='lawyer_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawyers.lawyer', verbose_name='Lawyer Reference'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='occupied_area',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Occupied Area'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='other_constraints_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.constrainttype', verbose_name='Other Constraints Type'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='prejudicial_registrations',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prejudicial Registrations'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reception_act',
            field=models.CharField(blank=True, choices=[('yes', 'si'), ('no', 'no')], default='no', max_length=100, null=True, verbose_name='Reception Area'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('Esproprio Agricolo', 'Agricultural expropriation'), ('Esproprio Residenziale Libera', 'Esproprio Residenziale Libera'), ('Esproprio Industriale Libera', 'Esproprio Industriale Libera'), ('Esproprio Fabbricato Residenziale', 'Esproprio Fabbricato Residenziale'), ('Esproprio Fabbricato Industriale', 'Esproprio Fabbricato Industriale')], default=None, max_length=100, null=True, verbose_name='Registration Typology'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='surface_directly_concerned',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Directly Concerned'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='target_data',
            field=models.CharField(max_length=100, null=True, verbose_name='Target Data'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=32, null=True, verbose_name='Target Value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
