# Generated by Django 3.1.7 on 2022-02-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0042_auto_20220220_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigation',
            old_name='starting_date',
            new_name='starting_data',
        ),
    ]
