# Generated by Django 3.1.7 on 2022-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0043_auto_20220220_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigation',
            old_name='target_data',
            new_name='target_date',
        ),
        migrations.RemoveField(
            model_name='litigation',
            name='closed',
        ),
        migrations.AlterField(
            model_name='litigation',
            name='above_ground_quantification',
            field=models.IntegerField(blank=True, default=0, help_text='Plant Name', null=True, verbose_name='Above Ground Quantification'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='closing_data',
            field=models.DateField(max_length=100, null=True, verbose_name='Closing Date'),
        ),
    ]
