# Generated by Django 3.1.7 on 2022-02-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0044_auto_20220220_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigation',
            old_name='closing_data',
            new_name='closing_date',
        ),
        migrations.RenameField(
            model_name='litigation',
            old_name='starting_data',
            new_name='starting_date',
        ),
    ]
