# Generated by Django 3.1.7 on 2022-02-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0048_litigation_hyperlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='closing_date',
            field=models.DateField(max_length=100, verbose_name='Closing Date'),
        ),
    ]
