# Generated by Django 3.1.7 on 2022-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0052_auto_20220226_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='turnover_margin',
        ),
        migrations.AddField(
            model_name='litigation',
            name='turnover_marg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Turnover Margin'),
        ),
    ]
