# Generated by Django 3.1.7 on 2022-02-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0053_auto_20220226_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigation',
            old_name='turnover_marg',
            new_name='turnover_margin',
        ),
    ]
