# Generated by Django 3.1.7 on 2022-02-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0054_auto_20220226_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='upload_pdf',
            field=models.FileField(default=1, upload_to='documents/', verbose_name='Upload File'),
            preserve_default=False,
        ),
    ]
