# Generated by Django 3.1.7 on 2022-02-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0055_litigation_upload_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='upload_pdf',
            field=models.FileField(upload_to='media/documents/', verbose_name='Upload File'),
        ),
    ]
