# Generated by Django 3.1.7 on 2022-03-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20220212_2051'),
        ('litigations', '0057_auto_20220301_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='culture_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.culturetype', verbose_name='Culture Type'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='upload_pdf',
            field=models.FileField(upload_to='documents/', verbose_name='Upload Contract'),
        ),
    ]
