# Generated by Django 3.1.7 on 2022-03-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0059_auto_20220303_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='above_ground_quantification',
            field=models.IntegerField(default=0, help_text='Plant Name', null=True, verbose_name='Above Ground Quantification'),
        ),
    ]
