# Generated by Django 3.1.7 on 2022-03-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0062_auto_20220303_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
