# Generated by Django 3.1.7 on 2022-03-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_auto_20220212_2051'),
        ('litigations', '0064_auto_20220303_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='above_ground_quantification',
            field=models.IntegerField(blank=True, default=0, help_text='Plant Name', null=True, verbose_name='Above Ground Quantification'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='culture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configurations.culturetype', verbose_name='Culture Type'),
        ),
    ]
