# Generated by Django 3.1.7 on 2022-03-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0065_auto_20220303_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='initial_estimation_value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Initial Estimation Value'),
        ),
    ]
