# Generated by Django 3.1.7 on 2022-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0066_auto_20220307_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='target_value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Target Value'),
        ),
    ]
