# Generated by Django 3.1.7 on 2022-03-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0067_auto_20220307_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='IMU_final_declaration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fianl Declaration IMU'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='contract_fee',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contract fee'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='enrollment_amount',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Enrollment Amount'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='epoch_construction',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Epoch Constrution'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='last_notary_fees',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Notary Fees'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='reclamation_cost',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reclamation Cost'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='residual_rent',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Residual Rent'),
        ),
    ]
