# Generated by Django 3.1.7 on 2022-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0068_auto_20220307_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='final_value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Final Value'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='revenue',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Revenue'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='total_cost',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='turnover_margin',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Turnover Margin'),
        ),
    ]
