# Generated by Django 3.1.7 on 2022-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0070_auto_20220312_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='above_ground_quantification',
            field=models.IntegerField(blank=True, help_text='Plant Name', null=True, verbose_name='Above Ground Quantification'),
        ),
    ]
