# Generated by Django 3.1.7 on 2022-03-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0071_auto_20220319_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='litigation',
            name='above_ground_quantification',
        ),
    ]
