# Generated by Django 3.1.7 on 2022-03-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0073_litigation_above_ground_quantification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='above_ground_quantification',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Above Ground Quantification'),
        ),
    ]
