# Generated by Django 3.1.7 on 2022-03-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0074_auto_20220319_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='value_list',
            field=models.CharField(blank=True, choices=[(1, '25%'), (2, '50%'), (3, '75%'), (4, '90%'), (5, '100%')], default='no', max_length=100, null=True, verbose_name='Value List'),
        ),
    ]
