# Generated by Django 3.1.7 on 2022-03-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0076_litigation_fee_percentuale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='fee_percentuale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fee Percentuale'),
        ),
    ]
