# Generated by Django 3.1.7 on 2022-03-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0078_auto_20220319_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='EBIt_percent',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='EBIt'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='fee_percentuale',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Fee Percentuale'),
        ),
    ]
