# Generated by Django 3.1.7 on 2022-03-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0080_auto_20220319_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigation',
            old_name='turnover_margin',
            new_name='EBIT',
        ),
    ]
