# Generated by Django 3.1.7 on 2022-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0081_auto_20220319_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='registration_type',
            field=models.CharField(choices=[(None, ''), ('Esproprio Agricolo', 'Agricultural expropriation'), ('Esproprio Residenziale Libera', 'Esproprio Residenziale Libera'), ('Esproprio Industriale Libera', 'Esproprio Industriale Libera'), ('Esproprio Fabbricato Residenziale', 'Esproprio Fabbricato Residenziale'), ('Esproprio Fabbricato Industriale', 'Esproprio Fabbricato Industriale'), ('Altre destinazioni funzionali', 'Altre destinazioni funzionali'), ('Area boschiva', 'Area boschiva'), ('Area industriale con fabbricati', 'Area industriale con fabbricati'), ('Area industriale senza fabbricati', 'Area industriale senza fabbricati'), ('Area Residenziale con fabbricati', 'Area Residenziale con fabbricati'), ('Area Residenziale senza fabbricati', 'Area Residenziale senza fabbricati'), ('Area Agricola con fabbricati', 'Area Agricola con fabbricati'), ('Area Agricola senza fabbricati', 'Area Agricola senza fabbricati')], default=None, max_length=100, null=True, verbose_name='Registration Typology'),
        ),
    ]
