# Generated by Django 3.1.7 on 2022-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0082_auto_20220320_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='EBIt_percent',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='EBIt %'),
        ),
    ]
