# Generated by Django 3.1.7 on 2022-03-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0085_remove_litigation_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
    ]
