# Generated by Django 3.1.7 on 2021-04-28 09:47

import contracts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('costStatements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=contracts.models.increment_contract_number, max_length=100, null=True, verbose_name='Codice')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data')),
                ('sign_date', models.DateField(blank=True, null=True, verbose_name='Data del segno')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='Cliente')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name='Cost Statement')),
            ],
        ),
    ]
