# Generated by Django 3.1.7 on 2021-12-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'contract', 'verbose_name_plural': 'contracts'},
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contract',
        ),
    ]
