# Generated by Django 3.1.7 on 2022-02-06 10:28

import contracts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_auto_20220206_1128'),
        ('costStatements', '0019_auto_20220206_1128'),
        ('contracts', '0002_auto_20211202_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(default=contracts.models.increment_contract_number, max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='sign-date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name='cost-statement'),
        ),
    ]
