# Generated by Django 3.1.7 on 2022-02-06 14:20

import contracts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0019_auto_20220206_1128'),
        ('clients', '0022_auto_20220206_1520'),
        ('contracts', '0003_auto_20220206_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(default=contracts.models.increment_contract_number, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name=''),
        ),
    ]
