# Generated by Django 3.1.7 on 2022-02-08 23:53

import contracts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20220209_0053'),
        ('costStatements', '0020_auto_20220206_1520'),
        ('contracts', '0004_auto_20220206_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(default=contracts.models.increment_contract_number, max_length=100, null=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='sign-date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name='cost-statement'),
        ),
    ]
