# Generated by Django 3.1.7 on 2022-02-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20220209_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'contract', 'verbose_name_plural': 'contracts'},
        ),
    ]
