# Generated by Django 3.1.7 on 2022-02-20 13:37

import contracts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20220220_1437'),
        ('costStatements', '0023_auto_20220210_1351'),
        ('contracts', '0006_auto_20220212_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='code',
            field=models.CharField(default=contracts.models.increment_contract_number, max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sign Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name='Cost Statement'),
        ),
    ]
