# Generated by Django 3.1.7 on 2022-02-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20220220_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='statement',
        ),
        migrations.AddField(
            model_name='contract',
            name='url',
            field=models.FloatField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
