# Generated by Django 3.1.7 on 2022-03-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20220301_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='url',
            field=models.FloatField(blank=True, max_length=400, null=True, verbose_name='Url'),
        ),
    ]
