# Generated by Django 3.1.7 on 2021-04-28 09:47

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome')),
                ('code', models.CharField(default=clients.models.increment_customer_number, max_length=20, unique=True, verbose_name='Codice')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Indirizzo e-mail')),
                ('phone', models.CharField(max_length=100, null=True, verbose_name='Telefono')),
                ('gender', models.CharField(blank=True, choices=[(None, ''), ('F', 'Femmina'), ('M', 'Maschio'), ('O', 'Altro')], default=None, max_length=10, null=True, verbose_name='Genere')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Compleanno')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Indirizzo')),
                ('customer_type', models.CharField(choices=[('individual', 'Individuo'), ('company', 'Azienda')], default='individual', max_length=16, null=True, verbose_name='Tipo di cliente')),
                ('is_customer', models.BooleanField(db_index=True, default=False, verbose_name='è cliente')),
                ('contacts', models.ManyToManyField(blank=True, related_name='_customer_contacts_+', to='clients.Customer', verbose_name='Contacts')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
