# Generated by Django 3.1.7 on 2021-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Città'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=100, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='post_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Numero postale'),
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Strada'),
        ),
    ]
