# Generated by Django 3.1.7 on 2021-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210430_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthplace',
            field=models.CharField(max_length=100, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=100, null=True, verbose_name="Nome dell'azienda"),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fiscal_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Codice fiscale'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Cognome'),
        ),
    ]
