# Generated by Django 3.1.7 on 2021-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210430_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(max_length=100, null=True, verbose_name='Persona di contatto'),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(max_length=100, null=True, verbose_name='Ruolo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascita'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Luogo di nascita'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codice fiscale'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefono'),
        ),
    ]
