# Generated by Django 3.1.7 on 2021-05-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='origin',
            field=models.CharField(blank=True, choices=[('internal', 'interno'), ('web', 'web')], default='internal', max_length=8, null=True, verbose_name='Origine'),
        ),
    ]
