# Generated by Django 3.1.7 on 2021-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_customer_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=256, null=True, verbose_name='Città/ Province'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=256, null=True, verbose_name='Strada'),
        ),
    ]
