# Generated by Django 3.1.7 on 2021-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20210504_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, ''), ('F', 'Femmina'), ('M', 'Maschio')], default=None, max_length=10, null=True, verbose_name='Genere'),
        ),
    ]
