# Generated by Django 3.1.7 on 2021-10-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
