# Generated by Django 3.1.7 on 2021-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_customer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='test',
        ),
        migrations.AddField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Partita IVA'),
        ),
    ]
