# Generated by Django 3.1.7 on 2021-10-31 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20211031_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fiscal_code',
            new_name='fisc_code',
        ),
    ]
