# Generated by Django 3.1.7 on 2021-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20211031_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='fiscal_code_individual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codice fiscale'),
        ),
    ]
