# Generated by Django 3.1.7 on 2021-11-07 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_customer_fiscal_code_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fiscal_code_individual',
        ),
    ]
