# Generated by Django 3.1.7 on 2022-02-08 23:53

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_auto_20220206_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthplace',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='birth-place'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=256, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default=clients.models.increment_customer_number, max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='company-name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='contact-person'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='_customer_contacts_+', to='clients.Customer', verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Individuo'), ('company', 'Azienda')], default='individual', max_length=16, null=True, verbose_name='customer-type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fiscal_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='fiscal-code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, ''), ('F', 'Femmina'), ('M', 'Maschio')], default=None, max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is-active'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is-customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='last-name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='origin',
            field=models.CharField(blank=True, choices=[('internal', 'interno'), ('web', 'web')], default='internal', max_length=8, null=True, verbose_name='origin'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post_number',
            field=models.CharField(max_length=100, null=True, verbose_name='post-number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street',
            field=models.CharField(max_length=256, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='vat-number'),
        ),
    ]
