# Generated by Django 3.1.7 on 2022-02-09 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20220209_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
    ]
