# Generated by Django 3.1.7 on 2022-02-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20220220_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_prefix',
            field=models.CharField(choices=[('+355', '+355'), ('+44', '+44')], default=None, max_length=100, null=True),
        ),
    ]
