# Generated by Django 3.1.7 on 2022-03-01 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0029_auto_20220301_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile_prefix',
        ),
    ]
