# Generated by Django 3.1.7 on 2022-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0031_customer_mobile_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hubspot_card',
            field=models.URLField(blank=True, max_length=7000, null=True, verbose_name='Hubspot Card'),
        ),
    ]
