# Generated by Django 3.1.7 on 2022-02-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0002_auto_20220226_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='margine_value',
        ),
        migrations.AddField(
            model_name='statistics',
            name='margin_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='final_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='initial_value',
            field=models.IntegerField(null=True, verbose_name='Initial Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='objective_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='revue_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_cost_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_value',
            field=models.IntegerField(null=True),
        ),
    ]
