# Generated by Django 3.1.7 on 2022-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0003_auto_20220226_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='final_value',
            field=models.IntegerField(null=True, verbose_name='Final Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='initial_value',
            field=models.IntegerField(default='$', null=True, verbose_name='Initial Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='margin_value',
            field=models.IntegerField(null=True, verbose_name='Margin Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='objective_value',
            field=models.IntegerField(null=True, verbose_name='Objective Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='revue_value',
            field=models.IntegerField(null=True, verbose_name='Revue Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_cost_value',
            field=models.IntegerField(null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_value',
            field=models.IntegerField(null=True, verbose_name='Total Value'),
        ),
    ]
