# Generated by Django 3.1.7 on 2022-02-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0004_auto_20220227_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='initial_value',
            field=models.IntegerField(default=0, null=True, verbose_name='Initial Value'),
        ),
    ]
