# Generated by Django 3.1.7 on 2022-02-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0006_auto_20220227_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='margin_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Margin Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Value'),
        ),
    ]
