# Generated by Django 3.1.7 on 2022-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0007_auto_20220228_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='final_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='initial_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initial Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='objective_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Objective Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='revue_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Revue Value'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_cost_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total Cost'),
        ),
    ]
