# Generated by Django 3.1.7 on 2022-03-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0009_auto_20220228_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'statistic', 'verbose_name_plural': 'statistics'},
        ),
    ]
