# Generated by Django 3.1.7 on 2022-03-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0010_auto_20220303_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='description',
        ),
    ]
