# Generated by Django 3.1.7 on 2022-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0011_remove_statistics_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='number',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Number'),
        ),
    ]
