# Generated by Django 3.1.7 on 2022-03-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0012_statistics_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='name',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
