# Generated by Django 3.1.7 on 2022-03-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0013_auto_20220306_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='name',
        ),
    ]
