# Generated by Django 3.1.7 on 2022-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0015_statistics_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
