# Generated by Django 3.1.7 on 2022-03-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0016_auto_20220306_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='name',
            new_name='title',
        ),
    ]
