# Generated by Django 3.1.7 on 2022-03-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0021_remove_statistics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='title',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number'),
        ),
    ]
