# Generated by Django 3.1.7 on 2022-03-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0023_auto_20220306_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='title',
        ),
    ]
