# Generated by Django 3.1.7 on 2022-03-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0024_remove_statistics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
