# Generated by Django 3.1.7 on 2022-03-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0025_statistics_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='ebit',
            field=models.FloatField(blank=True, null=True, verbose_name='EBIT'),
        ),
    ]
