# Generated by Django 3.1.7 on 2022-03-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0026_statistics_ebit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='ebit',
        ),
    ]
