# Generated by Django 3.1.7 on 2022-03-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0028_statistics_ebit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='margin_value',
        ),
        migrations.AddField(
            model_name='statistics',
            name='ebit_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='EBIT'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ebit',
            field=models.FloatField(blank=True, null=True, verbose_name='Margin Value'),
        ),
    ]
