# Generated by Django 3.1.7 on 2022-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0029_auto_20220320_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='ebit_percent',
        ),
        migrations.AddField(
            model_name='statistics',
            name='ebit_percent1',
            field=models.FloatField(blank=True, null=True, verbose_name='EBIT %'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ebit',
            field=models.FloatField(blank=True, null=True, verbose_name='EBIT '),
        ),
    ]
