# Generated by Django 3.1.7 on 2022-03-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0030_auto_20220320_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='ebit_percent1',
            new_name='ebit_percent',
        ),
    ]
