# Generated by Django 3.1.7 on 2022-03-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0031_auto_20220320_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='ebit',
            field=models.FloatField(blank=True, null=True, verbose_name='Ebit'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ebit_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Ebit_%'),
        ),
    ]
