# Generated by Django 3.1.7 on 2022-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0032_auto_20220321_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='ebit',
            field=models.FloatField(blank=True, null=True, verbose_name='ebit'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ebit_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='ebit_percent'),
        ),
    ]
