# Generated by Django 3.1.7 on 2022-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0033_auto_20220321_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='ebit',
            field=models.FloatField(blank=True, null=True, verbose_name='Ebit'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='ebit_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Ebit Percent'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='total_cost_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Cost Value'),
        ),
    ]
