# Generated by Django 3.1.7 on 2022-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0034_auto_20220322_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='total_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Moltiplicatore'),
        ),
    ]
