# Generated by Django 3.1.7 on 2022-04-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0035_auto_20220331_1036'),
        ('statistics_page', '0035_auto_20220331_2119'),
    ]

    operations = [
    ]
