# Generated by Django 3.1.7 on 2022-04-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_page', '0036_merge_20220404_1312'),
        ('statistics_page', '0036_merge_20220401_0802'),
    ]

    operations = [
    ]
