# Generated by Django 3.1.7 on 2021-12-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': 'lawyer', 'verbose_name_plural': 'lawyers'},
        ),
    ]
