# Generated by Django 3.1.7 on 2022-02-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_auto_20211202_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
