# Generated by Django 3.1.7 on 2022-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_auto_20220206_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
