# Generated by Django 3.1.7 on 2022-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_auto_20220206_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': 'Lawyer', 'verbose_name_plural': 'Lawyers'},
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
