# Generated by Django 3.1.7 on 2022-02-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_auto_20220209_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': 'lawyer', 'verbose_name_plural': 'lawyers'},
        ),
    ]
