# Generated by Django 3.1.7 on 2022-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0006_auto_20220212_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lawyer',
            options={'verbose_name': 'Lawyer', 'verbose_name_plural': 'Lawyers'},
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
