# Generated by Django 3.1.7 on 2021-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatement',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created date'),
        ),
    ]
