# Generated by Django 3.1.7 on 2021-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0002_coststatement_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatement',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Input Value'),
        ),
    ]
