# Generated by Django 3.1.7 on 2021-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0004_auto_20210428_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatementitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created date'),
        ),
    ]
