# Generated by Django 3.1.7 on 2021-04-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0005_coststatementitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatement',
            name='init_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Valore iniziale causa'),
        ),
    ]
