# Generated by Django 3.1.7 on 2021-04-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0006_coststatement_init_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='code',
            field=models.CharField(help_text='Code should not be changed as it is used in the cost statements report', max_length=8, null=True, verbose_name='Codice'),
        ),
    ]
