# Generated by Django 3.1.7 on 2021-05-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0008_remove_item_include_in_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coststatementitem',
            name='input_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='compute_code',
        ),
    ]
