# Generated by Django 3.1.7 on 2021-05-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0015_remove_coststatement_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatement',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name='Codice'),
        ),
    ]
