# Generated by Django 3.1.7 on 2022-02-06 14:20

import costStatements.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0031_auto_20220206_1128'),
        ('clients', '0022_auto_20220206_1520'),
        ('costStatements', '0019_auto_20220206_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coststatement',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='coststatementitem',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='hypothesis',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['priority'], 'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='code',
            field=models.CharField(max_length=20, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='expected_dealing_term',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='init_amount',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='init_negotiation',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='litigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='litigations.litigation', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='name',
            field=models.CharField(default=costStatements.models.increment_costStatement_number, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='cost_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='hypothesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.hypothesis', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.item', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.itemcategory', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='code',
            field=models.CharField(max_length=8, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
