# Generated by Django 3.1.7 on 2022-02-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0021_auto_20220209_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hypothesis',
            options={'verbose_name': 'hypothesis', 'verbose_name_plural': 'hypothesis-plural'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['priority'], 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='hypothesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.hypothesis', verbose_name='hypothesis'),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.item', verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.itemcategory', verbose_name='category'),
        ),
    ]
