# Generated by Django 3.1.7 on 2022-02-10 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('litigations', '0035_litigation_contract'),
        ('costStatements', '0022_auto_20220209_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coststatement',
            name='litigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='litigations.litigation', verbose_name='litigation'),
        ),
    ]
