# Generated by Django 3.1.7 on 2022-02-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0025_auto_20220220_1437'),
        ('litigations', '0045_auto_20220220_1324'),
        ('costStatements', '0023_auto_20220210_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coststatement',
            options={'verbose_name': 'cost Statement', 'verbose_name_plural': 'Cost Statements'},
        ),
        migrations.AlterModelOptions(
            name='coststatementitem',
            options={'verbose_name': 'Cost Statement Item', 'verbose_name_plural': 'Cost Statement Items'},
        ),
        migrations.AlterModelOptions(
            name='hypothesis',
            options={'verbose_name': 'Hypothesis', 'verbose_name_plural': 'hypothesis Plural'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['priority'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='expected_dealing_term',
            field=models.IntegerField(null=True, verbose_name='Expected dealing Term'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='init_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Init Amount'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='init_negotiation',
            field=models.IntegerField(null=True, verbose_name='Init Negotiation'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='litigation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='litigations.litigation', verbose_name='Litigation'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='coststatement',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='Total Cost'),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='cost_statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.coststatement', verbose_name='Cost Statement'),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='hypothesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.hypothesis', verbose_name='Hypothesis'),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='costStatements.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='coststatementitem',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hypothesis',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.IntegerField(blank=True, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='code',
            field=models.CharField(help_text='Code Change Message', max_length=8, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
    ]
