# Generated by Django 3.1.7 on 2022-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costStatements', '0024_auto_20220220_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='coststatement',
            name='url',
            field=models.FloatField(blank=True, null=True, verbose_name='Url'),
        ),
    ]
