# Generated by Django 3.1.7 on 2022-03-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='any_messi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='contenziosi_aperti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='contenziosi_definiti',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='contenziosi_trattativa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='ebit_da',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='percentuale_di_incremento',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='valore_iniziale_totale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='valore_obiettivo_totale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpi',
            name='valore_obiettivo_totale_in_trattativa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
