# Generated by Django 3.1.7 on 2022-04-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KPI', '0002_auto_20220322_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'verbose_name': 'KPI', 'verbose_name_plural': 'KPI'},
        ),
    ]
