# Generated by Django 3.1.7 on 2021-12-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatype',
            options={'verbose_name': 'area_type', 'verbose_name_plural': 'area_types'},
        ),
        migrations.AlterModelOptions(
            name='constrainttype',
            options={'verbose_name': 'constraint_type', 'verbose_name_plural': 'constraint_types'},
        ),
        migrations.AlterModelOptions(
            name='culturetype',
            options={'verbose_name': 'culture_type', 'verbose_name_plural': 'culture_types'},
        ),
        migrations.AlterModelOptions(
            name='disputematter',
            options={'verbose_name': 'dispute_matter', 'verbose_name_plural': 'dispute_matters'},
        ),
        migrations.AlterModelOptions(
            name='disputeobject',
            options={'verbose_name': 'dispute_object', 'verbose_name_plural': 'dispute_objects'},
        ),
        migrations.AlterModelOptions(
            name='reclamationinterventiontype',
            options={'verbose_name': 'reclamation_intervention_type', 'verbose_name_plural': 'reclamation_intervention_types'},
        ),
        migrations.AlterModelOptions(
            name='urbandestination',
            options={'verbose_name': 'urban_destination', 'verbose_name_plural': 'urban_destinations'},
        ),
    ]
