# Generated by Django 3.1.7 on 2022-02-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20220206_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatype',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='constrainttype',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='culturetype',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='disputematter',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='disputeobject',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='reclamationinterventiontype',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='urbandestination',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='areatype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='constrainttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='culturetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='disputematter',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='disputeobject',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='reclamationinterventiontype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='urbandestination',
            name='name',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
