# Generated by Django 3.1.7 on 2022-02-10 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_auto_20220209_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputematter',
            options={'verbose_name': 'Elion', 'verbose_name_plural': 'dispute-matters'},
        ),
    ]
