# Generated by Django 3.1.7 on 2022-02-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20220210_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disputematter',
            options={'verbose_name': 'dispute-matter', 'verbose_name_plural': 'dispute-matters'},
        ),
    ]
