# Generated by Django 3.1.7 on 2021-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Notificazione')),
                ('email_from', models.CharField(max_length=256, verbose_name='e-mail da')),
                ('recipients', models.CharField(blank=True, help_text="separare con; per più di un'e-mail. Se lasciato vuoto, verrà utilizzata l'email del modello", max_length=256, null=True, verbose_name='Destinatari')),
                ('notification_type', models.CharField(choices=[(None, ''), ('customer_registration', 'Modulo di registrazione del cliente'), ('litigation_form', 'Modulo contenzioso')], default=None, max_length=21, verbose_name='Tipo di notifica')),
                ('subject', models.TextField(null=True, verbose_name='Soggetto')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingMailServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=16, verbose_name='Server/ Host')),
                ('port', models.CharField(max_length=8, verbose_name='Port')),
                ('security_type', models.CharField(blank=True, choices=[(None, ''), ('TSL', 'TSL'), ('SSL', 'SSL')], default=None, max_length=10, null=True, verbose_name='Security Type')),
                ('user', models.CharField(blank=True, max_length=16, null=True, verbose_name='User')),
                ('password', models.CharField(blank=True, max_length=16, null=True, verbose_name='Password')),
            ],
        ),
    ]
