# Generated by Django 3.1.7 on 2021-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='password',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='User'),
        ),
    ]
