# Generated by Django 3.1.7 on 2021-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emailnotification_notify_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='possible_variables',
            field=models.TextField(null=True, verbose_name='Possibili variabili'),
        ),
    ]
