# Generated by Django 3.1.7 on 2021-05-04 10:31

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_emailnotification_possible_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='possible_variables',
            field=models.TextField(default=notifications.models.EmailNotification.get_all_fields, null=True, verbose_name='Possibili variabili'),
        ),
    ]
