# Generated by Django 3.1.7 on 2021-05-04 10:40

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20210504_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='possible_variables',
            field=models.TextField(default=notifications.models.EmailNotification.get_all_fields, help_text='da utilizzare nel campo del messaggio', null=True, verbose_name='Possibili variabili'),
        ),
    ]
