# Generated by Django 3.1.7 on 2021-05-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20210504_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='server',
            field=models.CharField(max_length=64, verbose_name='Server/ Host'),
        ),
    ]
