# Generated by Django 3.1.7 on 2021-12-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20210507_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'verbose_name': 'email_notification', 'verbose_name_plural': 'email_notifications'},
        ),
        migrations.AlterModelOptions(
            name='outgoingmailserver',
            options={'verbose_name': 'outgoing_mail_server', 'verbose_name_plural': 'outgoing_mail_server'},
        ),
        migrations.AlterModelTable(
            name='emailnotification',
            table='email_notification',
        ),
        migrations.AlterModelTable(
            name='outgoingmailserver',
            table='outgoing_mail_server',
        ),
    ]
