# Generated by Django 3.1.7 on 2022-02-06 10:28

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20211202_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'verbose_name': 'email-notification', 'verbose_name_plural': 'email-notifications'},
        ),
        migrations.AlterModelOptions(
            name='outgoingmailserver',
            options={'verbose_name': 'outgoing-mail-server', 'verbose_name_plural': 'outgoing-mail-server'},
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='email_from',
            field=models.CharField(max_length=256, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='message',
            field=models.TextField(null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='name',
            field=models.CharField(max_length=256, verbose_name='notifications'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[(None, ''), ('customer_registration', 'customer-registration'), ('litigation_form', 'litigation-form')], default=None, max_length=21, verbose_name='notifications-type'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notify_on',
            field=models.CharField(choices=[('form_submit', 'form-send'), ('url_click', 'click-on-url')], default='form_submit', max_length=21, verbose_name='notifications-on'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='possible_variables',
            field=models.TextField(default=notifications.models.EmailNotification.get_all_fields, help_text='used-in-message-field', null=True, verbose_name='possible-variables'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='recipients',
            field=models.CharField(blank=True, help_text="separare con; per più di un'e-mail. Se lasciato vuoto,                     verrà utilizzata l'email del modello", max_length=256, null=True, verbose_name='recipients'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(max_length=256, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='password',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='user'),
        ),
    ]
