# Generated by Django 3.1.7 on 2022-02-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20220209_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='recipients',
            field=models.CharField(blank=True, help_text='separate with; for more than one email. If left blank,                      the model email will be used', max_length=256, null=True, verbose_name='recipients'),
        ),
    ]
