# Generated by Django 3.1.7 on 2022-02-20 13:37

from django.db import migrations, models
import notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_auto_20220215_0527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotification',
            options={'verbose_name': 'Email Notification', 'verbose_name_plural': 'Email Notifications'},
        ),
        migrations.AlterModelOptions(
            name='outgoingmailserver',
            options={'verbose_name': 'Outgoing Mail Server', 'verbose_name_plural': 'Outgoing Mail Server'},
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Notifications'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification_type',
            field=models.CharField(choices=[(None, ''), ('customer_registration', 'Customer Registration'), ('litigation_form', 'Litigation Form')], default=None, max_length=21, verbose_name='Notifications Type'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notify_on',
            field=models.CharField(choices=[('form_submit', 'Form Send'), ('url_click', 'Click On Url')], default='form_submit', max_length=21, verbose_name='Notifications On'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='possible_variables',
            field=models.TextField(default=notifications.models.EmailNotification.get_all_fields, help_text='Used In Message Field', null=True, verbose_name='Possible Variables'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='recipients',
            field=models.CharField(blank=True, help_text='Separate with; for more than one email. If left blank,                      the model email will be used', max_length=256, null=True, verbose_name='Recipients'),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='subject',
            field=models.CharField(max_length=256, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='password',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='port',
            field=models.CharField(max_length=8, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='security_type',
            field=models.CharField(blank=True, choices=[(None, ''), ('TLS', 'TLS'), ('SSL', 'SSL')], default=None, max_length=10, null=True, verbose_name='Security Type'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='server',
            field=models.CharField(max_length=64, verbose_name='Server Host'),
        ),
        migrations.AlterField(
            model_name='outgoingmailserver',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='User'),
        ),
    ]
